### ISSUE TITLE
[Bug] Not all Actors displayed after Items Per Page set

### ISSUE THREAD

**Issue by firewalkwithme93** [curtwagner1984/YAPO#28] opened 2016-08-27 14:23 UTC
I've found that when I set a custom Items Per Page amount (above the default 25), the listings in the Actors section only go so far alphabetically. For example, normally I have six pages of actors from A-Z, but when I set it to say, 100, the amount of Actors displayed on each page is the same but there's only 2 pages and it stops at D. I think perhaps the lessened amount of pages corresponds to the new 100 item limit but the actual list hasn't increased in amount.

**Comment by sjclayton** [comment] 2016-08-27 14:37
@firewalkwithme93 This appears to be a loading / refresh issue, if you do a force refresh after on the Actor page after changing the Items Per Page setting it should display properly.

Clearly a bug however, yes!

**Comment by curtwagner1984** [comment] 2016-08-27 15:36
Should work as intended now.

**Comment by sjclayton** [comment] 2016-08-27 15:47
@curtwagner1984 Appears to be good - can probably close this now.

**Closed** 2016-08-27 17:52 UTC
